### ISSUE TITLE
Where to run fetch_data.sh?

### ISSUE THREAD

**Issue by clemsciences** [ufal/evalatin2024-latinpipe#1]
Hello,

Great paper and I even watched your presentation at LT4HALA 2024 workshop.

After having made fetch_data.sh runnable (`chmod +x fetch_data.sh`), I tried to run ./data/fetch_data.sh and all the directories were in the root directory.
I ran 
```bash
la_ud213_all="la_ittb la_llct la_perseus la_proiel la_udante"
la_other="la_archimedes la_sabellicus"
transformer="bowphs/PhilBerta"  # or bowphs/LaBerta

latinpipe_evalatin24.py $(for split in dev test train; do echo --$split; for tb in $la_ud213_all; do [ $tb-$split = la_proiel-train ] && tb=la_proielh; echo data/$tb/$tb-ud-$split.conllu; done; done) $(for tb in $la_other; do echo data/$tb/$tb-train.conllu; done) --transformers $transformer --epochs=30 --exp=evalatin24_model --subword_combination=last --epochs_frozen=10 --batch_size=64 --save_checkpoint
```
but it failed with 
> Traceback (most recent call last):
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 935, in <module>
    main([] if "__file__" not in globals() else None)
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 860, in main
    train = UDDatasetMerged([UDDataset(path, args, treebank_id=i if args.treebank_ids else None) for i, path in enumerate(args.train)])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 860, in <listcomp>
    train = UDDatasetMerged([UDDataset(path, args, treebank_id=i if args.treebank_ids else None) for i, path in enumerate(args.train)])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 97, in __init__
    with open(path, "r", encoding="utf-8") if text is None else io.StringIO(text) as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/la_ittb'

The same occurs when I run (`data/$tb` became `$tb`)

```bash
latinpipe_evalatin24.py $(for split in dev test train; do echo --$split; for tb in $la_ud213_all; do [ $tb-$split = la_proiel-train ] && tb=la_proielh; echo $tb/$tb-ud-$split.conllu; done; done) $(for tb in $la_other; do echo data/$tb/$tb-train.conllu; done) --transformers $transformer --epochs=30 --exp=evalatin24_model --subword_combination=last --epochs_frozen=10 --batch_size=64 --save_checkpoint
```
and it failed with

> Traceback (most recent call last):
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 935, in <module>
    main([] if "__file__" not in globals() else None)
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 860, in main
    train = UDDatasetMerged([UDDataset(path, args, treebank_id=i if args.treebank_ids else None) for i, path in enumerate(args.train)])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 860, in <listcomp>
    train = UDDatasetMerged([UDDataset(path, args, treebank_id=i if args.treebank_ids else None) for i, path in enumerate(args.train)])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clement/PycharmProjects/evalatin2024-latinpipe/./latinpipe_evalatin24.py", line 97, in __init__
    with open(path, "r", encoding="utf-8") if text is None else io.StringIO(text) as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'la_ittb'

What should I change in order to fix it?

**Comment by foxik** [comment]
Hi,

the script should be run in the `data` directory directly -- I updated the `README.md` with the exact command to run (BTW, you do not need to change the executable status of `fetch_data.sh`, you can instead run just `sh fetch_data.sh` -- for scripts I do not want to run often I do not set their executable bit to avoid running them by mistake).
