### ISSUE TITLE
ValueError: Argument `decay_steps` must be > 0. Received: decay_steps=-1880

### ISSUE THREAD

**Issue by locusclassicus** [ufal/evalatin2024-latinpipe#4]
The error I have been receiving after 10 warmup epochs is 

```
ValueError: Argument `decay_steps` must be > 0. Received: decay_steps=-1880
```

I have tried to fix it in various ways, but it is all in vain.

**Comment by foxik** [comment]
When training, then:
- first the `--epochs_frozen` epochs of frozen training is performed (to correctly pretrain the LSTM layers for contextualizing the gold UPOS tags; if you do not use gold UPOS tags, you can skip this phase and not use the LSTM layers)
- then the `--epochs` epochs of training is performed; of these epochs, the first `--learning_rate_warmup` updates perform the warmup of the learning rate.

  For this to make sense, you have to make sure that `--epochs * batches_per_epoch` >= `--learning_rate_warmup`, where `batches_per_epoch` is either:
  - the number of sentences in the train data divided by the batch size, if you use a single training treebank, or
  - `--steps_per_epoch`, if you use multiple training treebanks.

  BTW, this distinction is handled by https://github.com/ufal/evalatin2024-latinpipe/blob/60b1fb56a8e8daed377a87222915ba428fb4f6ae/latinpipe_evalatin24.py#L487-L491.

The `decay_steps`, which are `-1880` in your case, is the `--epochs * batches_per_epoch - --learning_rate_warmup`.

**Comment by locusclassicus** [comment]
Great, I did not realise that --steps_per_epoch = batches_per_epoch. This problem is now fixed, thank you!
